namespace ApiWebGeradorPessoa.Services
{
    public class NomeSobrenome
    {
        public List<string> nomes = new List<string>();

        public NomeSobrenome()
        {
            nomes = new List<string>
            {
                "Ana Souza",
                "Bruno Oliveira",
                "Carlos Pereira",
                "Daniela Ferreira",
                "Eduardo Lima",
                "Fernanda Santos",
                "Guilherme Alves",
                "Helena Costa",
                "Igor Martins",
                "Juliana Rodrigues",
                "Kevin Mendes",
                "Larissa Araújo",
                "Marcelo Barbosa",
                "Natália Pinto",
                "Otávio Ramos",
                "Patrícia Silva",
                "Rafael Moreira",
                "Sabrina Gomes",
                "Tiago Vieira",
                "Vanessa Monteiro",
                "Alexandre Ribeiro",
                "Bianca Castro",
                "Caio Teixeira",
                "Débora Carvalho",
                "Enzo Duarte",
                "Fabiana Cardoso",
                "Gabriel Borges",
                "Heloísa Freitas",
                "Ítalo Almeida",
                "Joyce Farias",
                "Leonardo Pires",
                "Mariana Fonseca",
                "Nicolas Lopes",
                "Olivia Brito",
                "Pedro Macedo",
                "Queila Nascimento",
                "Renan Rocha",
                "Simone Campos",
                "Thiago Moura",
                "Ulysses Cunha",
                "Verônica Silva",
                "Wesley Correia",
                "Xênia Xavier",
                "Yuri Antunes",
                "Zilda Assis",
                "Amélia Viana",
                "Bruno Lima",
                "Carolina Barros",
                "Daniel Ferreira",
                "Elisa Martins",
                "Felipe Oliveira",
                "Giovana Santos",
                "Henrique Costa",
                "Ingrid Pereira",
                "João Mendes",
                "Karina Rodrigues",
                "Lucas Moreira",
                "Manuela Alves",
                "Natan Souza",
                "Olívia Castro",
                "Paulo Araújo",
                "Queila Lima",
                "Rafael Vieira",
                "Sofia Pinto",
                "Tomás Silva",
                "Ulisses Monteiro",
                "Valéria Ferreira",
                "William Teixeira",
                "Xavier Cardoso",
                "Yara Macedo",
                "Zenon Barbosa",
                "Arthur Lima",
                "Beatriz Santos",
                "Caio Oliveira",
                "Diana Costa",
                "Eduardo Pereira",
                "Fernanda Mendes",
                "Gustavo Ferreira",
                "Helena Alves",
                "Ítalo Rodrigues",
                "Julia Cardoso",
                "Lucas Vieira",
                "Maria Fonseca",
                "Nicolas Almeida",
                "Otávio Campos",
                "Paulo Farias",
                "Quitéria Moreira",
                "Raquel Pires",
                "Samuel Freitas",
                "Talita Moura",
                "Ulisses Rocha",
                "Valter Cunha",
                "Wagner Assis",
                "Xênia Silva",
                "Yasmin Correia",
                "Zé Antunes",
                "Amanda Viana",
                "Bernardo Duarte",
                "Clara Carvalho",
                "Diogo Brito",
                "Adriana Ferreira",
                "Benício Sousa",
                "Carolina Mendes",
                "Diego Carvalho",
                "Elisabete Cardoso",
                "Felipe Vieira",
                "Gabriela Antunes",
                "Hugo Lima",
                "Isabela Nunes",
                "João Monteiro",
                "Karine Rocha",
                "Leonardo Cunha",
                "Marina Ribeiro",
                "Natália Silva",
                "Otávio Almeida",
                "Pedro Barros",
                "Quezia Santos",
                "Rafael Martins",
                "Sabrina Pinto",
                "Tatiana Gomes",
                "Ugo Pereira",
                "Vanessa Lima",
                "Wesley Souza",
                "Xavier Barros",
                "Yara Ferreira",
                "Zeca Duarte",
                "Ana Paula Almeida",
                "Bruno Cardoso",
                "Clara Vieira",
                "Daniel Antunes",
                "Eduardo Santos",
                "Fernanda Cunha",
                "Gustavo Monteiro",
                "Helena Rocha",
                "Igor Almeida",
                "Julia Nunes",
                "Kevin Carvalho",
                "Larissa Sousa",
                "Marcos Lima",
                "Nathalia Cardoso",
                "Olívia Mendes",
                "Paulo Antunes",
                "Quirino Gomes",
                "Ricardo Pereira",
                "Simone Lima",
                "Tatiane Souza",
                "Ulisses Barros",
                "Victor Ferreira",
                "Willian Duarte",
                "Xênia Cardoso",
                "Yago Vieira",
                "Zélia Antunes",
                "Alessandra Santos",
                "Bruno Cunha",
                "Catarina Monteiro",
                "Diego Rocha",
                "Eliane Almeida",
                "Fábio Nunes",
                "Gisele Carvalho",
                "Henrique Sousa",
                "Isabel Lima",
                "João Cardoso",
                "Katia Mendes",
                "Luan Antunes",
                "Mariana Gomes",
                "Nicolas Pereira",
                "Otávio Lima",
                "Paula Souza",
                "Quintino Barros",
                "Renata Ferreira",
                "Sérgio Duarte",
                "Thaís Cardoso",
                "Uriel Vieira",
                "Valéria Antunes",
                "Walter Santos",
                "Ximena Cunha",
                "Yuri Monteiro",
                "Zélio Rocha",
                "Aline Almeida",
                "Bernardo Nunes",
                "Cláudio Carvalho",
                "Daniela Sousa",
                "Eduardo Lima",
                "Felipe Cardoso",
                "Gustavo Mendes",
                "Helena Antunes",
                "Inácio Gomes",
                "José Pereira",
                "Karla Lima",
                "Lívia Souza",
                "Marcelo Barros",
                "Natália Ferreira",
                "Otávio Duarte",
                "Priscila Cardoso",
                "Quirino Vieira",
                "Rafaela Antunes",
                "Samuel Santos",
                "Tatiana Cunha",
                "Ulisses Monteiro",
                "Verônica Rocha",
                "William Almeida",
                "Xênia Nunes",
                "Yasmin Carvalho",
                "Zeca Sousa",
                "Aline Lima",
                "Bruno Cardoso",
                "Camila Mendes",
                "Diego Antunes",
                "Elisa Gomes",
                "Felipe Pereira",
                "Gabriela Lima",
                "Hugo Souza",
                "Isabel Barros",
                "João Ferreira",
                "Katia Duarte",
                "Leonardo Cardoso",
                "Marta Vieira",
                "Nicolas Antunes",
                "Olívia Santos",
                "Paulo Cunha",
                "Quezia Monteiro",
                "Renan Rocha",
                "Sabrina Almeida",
                "Thiago Nunes",
                "Uriel Carvalho",
                "Vinícius Sousa",
                "Wesley Lima",
                "Ximena Cardoso",
                "Yara Mendes",
                "Zélia Antunes",
                "Adriana de Oliveira",
                "Bernardo da Costa",
                "Camila dos Santos",
                "Diego de Souza",
                "Eliana da Silva",
                "Felipe de Carvalho",
                "Gabriela dos Reis",
                "Henrique de Andrade",
                "Isabel da Rocha",
                "José dos Anjos",
                "Karen de Melo",
                "Leonardo da Luz",
                "Marcelo dos Passos",
                "Natália de Brito",
                "Olívia da Cunha",
                "Pedro dos Campos",
                "Quirino de Farias",
                "Renata da Silva",
                "Samuel de Lima",
                "Tatiana dos Reis",
                "Ulisses de Carvalho",
                "Vera da Costa",
                "Wagner dos Santos",
                "Xavier de Souza",
                "Yara da Silva",
                "Zeca de Almeida",
                "Alessandra dos Santos",
                "Benedito de Oliveira",
                "Camila da Costa",
                "Daniel de Souza",
                "Elisabeth dos Reis",
                "Fábio de Andrade",
                "Gabriela da Rocha",
                "Henrique dos Anjos",
                "Isabela de Melo",
                "João da Luz",
                "Kátia dos Passos",
                "Lucas de Brito",
                "Mariana da Cunha",
                "Natália dos Campos",
                "Otávio de Farias",
                "Paula da Silva",
                "Quirino de Lima",
                "Rafaela dos Reis",
                "Simone de Carvalho",
                "Thiago da Costa",
                "Ursula dos Santos",
                "Vinícius de Souza",
                "Wesley da Silva",
                "Ximena de Almeida",
                "Yuri dos Santos",
                "Zélia de Oliveira"
            };

        }
    }
}
